a = input("Digite algo: ")
print("O tipo primitivo desse valor é:", type)
print("Só tem espaços? ", a.isspace())
print("È um número? ", a.isnumeric())
print("È alfabético? ", a.isalpha())
print("È um alfanumérico? ", a.isalnum())
print("Está em maiúsculas? ", a.isupper())
print("Está em minúsculas? ", a.islower())
print("Está capitalizada? ", a.istitle())

#Aprendendo método boleano (true, false)